language: node_js
node_js:
- "stable"
install:
  - npm install
script:
  - npm test
  - npm run coverage
env:
  - NODE_ENV=test
  global:
    - CC_TEST_REPORTER_ID=d65fad6a3438a6931af676591bc552704194626144e42bfaff3b8664b6cab9a8
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - createuser postgres -s -U postgres
  - createdb businesses --username=postgres
  - sequelize db:migrate
  - sequelize db:seed:all
after_success :
    - npm run coverage
