language: node_js
dist: trusty
node_js:
- "node"
install:
  - npm install
env:
  - NODE_ENV=development
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
   - psql -c 'create database businesses;' -U postgres
script:
  - npm test
after_success :
    - npm run coverage

