language: node_js
node_js:
- "stable"
install:
  - npm install
script:
  - npm test
  - npm run coverage
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - createuser postgres -s -U postgres
  - createdb businesses --username=postgres
  - sequelize db:migrate
  - sequelize db:seed:all
  