language: node_js
node_js:
- "9"
install:
  - npm install
env:
  - DB=postgres://postgres@127.0.0.1/test
cache:
  directories:
    - "node_modules"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
   - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE test;' -U postgres; fi"
script:
  - npm test
  - npm run coverage
after_success :
    - npm run coverage

