language: node_js
node_js:
- "stable"
install:
  - npm install
script:
  - npm test
  - npm run coverage
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - createuser aukhulpz -s -U postgres
  - createdb database_test --username=aukhulpz
  - sequelize db:migrate
  - sequelize db:seed:all
after_success :
    - npm run coverage