language: node_js
node_js:
- "node"
before_install:
  - npm i -g npm
install: true
before_script:
  - npm install
script:
  - nodemon --exec babel-node --presets es2015 ./server/bin/www &
  - nyc --reporter=html --reporter=text mocha ./server/test/ --exit --compilers js:babel-register
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"