language: node_js
node_js:
- "node"
- "9"
before_install:
  - npm i -g npm@version-number
before_script:
  - npm install
script:
  - nodemon --exec babel-node --presets es2015 ./bin/www &
  - nyc --reporter=html --reporter=text mocha ./test/ --compilers js:babel-register | ./node_modules/coveralls/bin/coveralls.js
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=03C09Hg7paw3OYtGXxZDmEErnd4kPqJaH
  